export const AGREGAR_ENTRADA  = 'AGREGAR_ENTRADA';
export const AGREGAR_ENTRADA_EXITO  = 'AGREGAR_ENTRADA_EXITO';
export const AGREGAR_ENTRADA_ERROR  = 'AGREGAR_ENTRADA_ERROR';

export const DESCARGA_INICIADA  = 'DESCARGA_INICIADA';
export const DESCARGA_TERMINADA  = 'DESCARGA_TERMINADA';
export const DESCARGA_FALLIDA  = 'DESCARGA_FALLIDA';

export const OBTENER_ENTRADA_ELIMINAR  = 'OBTENER_ENTRADA_ELIMINAR';
export const ENTRADA_ELIMINADA_OK  = 'ENTRADA_ELIMINADA_OK';
export const ENTRADA_ELIMINADA_FALLA  = 'ENTRADA_ELIMINADA_FALLA';

export const OBTENER_ENTRADA_EDITAR  = 'OBTENER_ENTRADA_EDITAR';
export const INICIAR_EDICION_ENTRADA  = 'INICIAR_EDICION_ENTRADA';
export const ENTRADA_EDITADA_OK  = 'ENTRADA_EDITADA_OK';
export const ENTRADA_EDITADA_FALLA  = 'ENTRADA_EDITADA_FALLA';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';